rss:
  openai_api_base: https://openkey.cloud/v1
  max_entry: 100
  base: docs/
  feed:
    - name: 知乎每日精选
      description: 知乎每日精选
      summarize: true
      urls:
        - https://www.zhihu.com/rss
