rss:
  openai_api_base: https://openkey.cloud/v1
  max_entry: 100
  base: docs/
  feed:
#    - name: Test
#      summarize: true
#      urls:
#        - https://www.elastic.co/blog/feed
    - name: Aggregate
      description: Blog aggregation for some
      summarize: true
      urls:
        - https://goteleport.com/blog/rss.xml
        - https://engineering.mercari.com/en/blog/feed.xml
        - https://blog.replit.com/feed.xml
        - https://abhinavsarkar.net/tags/programming/feed.atom
        - https://httptoolkit.tech/rss.xml
        - https://engineering.freeagent.com/feed/
        - https://severalnines.com/rss.xml
        - https://learnk8s.io/rss.xml
        - https://v8.dev/blog.atom
        - https://technology.customink.com/feed.xml
        - http://blog.avenuecode.com/rss.xml
        - https://8thlight.com/blog/feed/atom.xml
        - http://blog.arkency.com/atom.xml
        - http://artsy.github.io/feed
        - https://www.bigeng.io/rss/
        - https://advancedweb.hu/atom.xml
        - https://auth0.com/blog/rss.xml
        - https://capgemini.github.io/feed.xml
        - https://aws.amazon.com/blogs/aws/feed/
        - https://code.blender.org/rss
        - http://www.codenameone.com/feed.xml
        - https://spin.atomicobject.com/feed/
        - https://blog.developer.bazaarvoice.com/feed/
        - https://blog.cloudflare.com/rss/
        - https://developer.atlassian.com/blog/feed.xml
        - https://blog.cloudera.com/feed/
        - https://www.confluent.io/feed/
        - https://tech.buzzfeed.com/feed
        - https://engineering.brandwatch.com/rss/
        - https://benchling.engineering/feed
        - https://www.elastic.co/blog/feed
        - http://deliveroo.engineering/feed.xml
        - https://techblog.commercetools.com/feed
        - https://databricks.com/feed
        - https://deezer.io/feed
        - https://engineering.fb.com/feed/
        - https://codeascraft.com/feed/
        - https://medium.com/feed/feedzaitech
        - https://tech.findmypast.com/feed.xml
        - https://code.fb.com/feed/
        - https://www.eventbrite.com/engineering/feed/
        - https://evernote.com/blog/feed/
        - https://drivy.engineering/feed.xml
        - https://evilmartians.com/chronicles.atom
        - https://www.ebayinc.com/stories/blogs/tech/rss/
        - http://feeds.feedburner.com/GoogleOnlineSecurityBlog
        - https://galois.com/feed/
        - https://githubengineering.com/atom.xml
        - https://blog.digitalocean.com/rss/
        - https://www.hashicorp.com/blog/feed.xml
        - https://collectiveidea.com/blog/feed/
        - http://feeds.feedburner.com/blogspot/gJZg
        - http://engineering.grab.com/feed.xml
        - https://engineering.gusto.com/rss/
        - https://www.hostinger.com/blog/feed/
        - https://engineering.doximity.com/feed
        - https://www.cockroachlabs.com/blog/index.xml
        - https://product.hubspot.com/blog/rss.xml
        - https://lambda.grofers.com/feed
        - https://dropbox.tech/feed
        - https://engineering.hashnode.com/rss.xml
        - https://kinvolk.io/blog/index.xml
        - https://tech.instacart.com/feed
        - https://kolosek.com/rss/
        - https://blog.heroku.com/engineering/feed
        - https://hashrocket.com/blog.rss
        - https://jobandtalent.engineering/feed
        - https://blog.imgur.com/feed/
        - https://nordicapis.com/feed/
        - https://blog.novoda.com/rss/
        - https://developer.okta.com/feed.xml
        - https://eng.lyft.com/feed
        - http://blog.memsql.com/feed/
        - https://engineering.mixpanel.com/feed/
        - https://medium.engineering/feed
        - http://blog.apps.npr.org/atom.xml
        - https://engblog.nextdoor.com/feed
        - https://hacks.mozilla.org/feed/
        - https://developers.redhat.com/blog/feed/atom/
        - https://tech.olx.com/feed
        - https://postmarkapp.com/blog/feed.atom
        - http://engineering.remind.com/feed.xml
        - https://tech.showmax.com/feed.xml
        - https://multithreaded.stitchfix.com/feed.xml
        - https://labs.spotify.com/feed/
        - https://www.stridenyc.com/blog/rss.xml
        - https://technology.skybettingandgaming.com/feed.xml
        - https://umbrella.cisco.com/blog/feed/
        - https://www.surveymonkey.com/feed/
        - https://engineering.prezi.com/feed
        - https://semaphoreci.com/community/tutorials.atom
        - https://developer.salesforce.com/blogs/feed
        - https://mesosphere.com/feed/
        - https://feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots
        - https://www.toptal.com/blog.rss
        - https://slack.engineering/feed
        - http://semaphoreci.com/blog/engineering.xml
        - https://blog.siftscience.com/feed/
        - https://stackoverflow.blog/feed/
        - http://techblog.thescore.com/feed.xml
        - https://tech.trivago.com/index.xml
        - https://www.thoughtworks.com/rss/insights.xml
        - https://bytes.swiggy.com/feed
        - http://engineering.vinted.com//atom.xml
        - https://developers.soundcloud.com/blog.rss
        - https://blog.timescale.com/feed
        - https://engineering.tumblr.com/rss
        - http://eng.wealthfront.com/feed/
        - https://www.sitepoint.com/feed/
        - https://stripe.com/blog/feed.rss
        - http://engineering.wingify.com/atom.xml
        - https://infrequently.org/feed/
        - https://www.amitmerchant.com/feed.xml
        - https://buildingvts.com/feed
        - http://addyosmani.com/rss.xml
        - https://engineeringblog.yelp.com/feed.xml
        - https://alanstorm.com/feed/feed.xml
        - https://ariya.io/index.xml
        - https://tech.xing.com/feed
        - http://tenderlovemaking.com/atom.xml
        - https://www.devroom.io/index.xml
        - https://carlosbecker.com/index.xml
        - https://developerblog.zendesk.com/feed
        - https://bohops.com/feed/
        - http://lucumr.pocoo.org/feed.atom
        - http://nullprogram.com/feed/
        - https://code.dblock.org/feed.xml
        - http://www.brendangregg.com/blog/rss.xml
        - https://www.dereuromark.de/feed/
        - https://domenicoluciani.com/feed.xml
        - https://blog.filippo.io/rss/
        - https://hookrace.net/blog/feed/
        - https://dotdev.co/feed/
        - https://ericlippert.com/feed/
        - https://tomassetti.me/feed/
        - http://www.evanjones.ca/index.rss
        - https://deanhume.com/rss/
        - http://feeds.feedburner.com/HighScalability
        - https://erikrunyon.com/feed.xml
        - https://drewdevault.com/feed.xml
        - https://www.chenhuijing.com/feed.xml
        - https://www.metachris.com/index.xml
        - https://elegantcode.com/feed/
        - https://conductofcode.io/feed.xml
        - https://glebbahmutov.com/blog/atom.xml
        - https://eli.thegreenplace.net/feeds/all.atom.xml
        - https://henrikwarne.com/feed/
        - https://davidwalsh.name/feed/atom
        - https://jeremykun.com/feed/
        - https://tympanus.net/codrops/rss
        - http://jakewharton.com/feed.xml
        - https://jes.al/atom.xml
        - https://jvns.ca/atom.xml
        - https://codeblog.jonskeet.uk/feed/
        - https://adambard.com/blog/feed.xml
        - https://useyourloaf.com/blog/rss.xml
        - https://jerrygamblin.com/feed/
        - https://idea.popcount.org/rss.xml
        - https://maryrosecook.com/blog/feed.xml
        - https://begriffs.com/atom.xml
        - http://matt.might.net/articles/feed.rss
        - https://martinfowler.com/feed.atom
        - https://blog.sleeplessbeastie.eu/feed.xml
        - https://blog.cryptographyengineering.com/feed/
        - http://blog.fogus.me/feed/
        - https://blog.rinesi.com/feed/
        - https://snook.ca/jonathan/index.rdf
        - https://www.mattcutts.com/blog/feed/
        - http://www.windytan.com/feeds/posts/default
        - https://aphyr.com/posts.atom
        - http://blog.pamelafox.org/feeds/posts/default
        - https://oleb.net/blog/atom.xml
        - https://blogs.msdn.microsoft.com/oldnewthing/feed
        - https://realpython.com/atom.xml
        - http://blog.cleancoder.com/atom.xml
        - https://akrabat.com/feed/
        - https://www.thepolyglotdeveloper.com/blog/index.xml
        - https://eviltrout.com/feed.xml
        - https://joshtronic.com/atom.xml
        - http://feeds.hanselman.com/ScottHanselman
        - https://blog.nelhage.com/atom.xml
        - http://blog.rtwilson.com/feed/
        - http://www.catonmat.net/feed/
        - https://neverfriday.com/feed/
        - http://thedailywtf.com/rss
        - https://vladmihalcea.com/feed/
        - https://www.yegor256.com/rss.xml
        - https://muffinman.io/atom.xml
        - https://www.ardanlabs.com/blog/index.xml
        - https://blog.getbootstrap.com/feed.xml
        - https://zachholman.com/atom.xml
        - https://ipfs.io/blog/index.xml
        - https://blog.golang.org/feed.atom
        - https://blog.jooq.org/feed/
        - https://blogs.msdn.microsoft.com/dotnet/feed/
        - http://raganwald.com/atom.xml
        - https://blogs.windows.com/msedgedev/rss
        - https://blog.jetbrains.com/kotlin/feed/
        - https://tania.dev/rss.xml
        - https://swizec.com/blog/feed